# Generated by Django 3.2.13 on 2022-04-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=30, verbose_name='Banco origem')),
                ('agencia_origem', models.CharField(max_length=10, verbose_name='Agência origem')),
                ('conta_origem', models.CharField(max_length=20, verbose_name='Conta origem')),
                ('banco_destino', models.CharField(max_length=30, verbose_name='Banco destino')),
                ('agencia_destino', models.CharField(max_length=10, verbose_name='Agência destino')),
                ('conta_destino', models.CharField(max_length=20, verbose_name='Conta destino')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('data', models.DateField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['data_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.UniqueConstraint(fields=('banco_origem', 'agencia_origem', 'conta_origem', 'banco_destino', 'agencia_destino', 'conta_destino', 'data'), name='unique_transacao'),
        ),
    ]
