# Generated by Django 3.2.13 on 2022-04-22 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
