# Generated by Django 3.2.13 on 2022-04-12 15:11

from django.db import migrations, models
import transacao.validators.csv_file


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0004_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_csv/', validators=[transacao.validators.csv_file.is_csv_file, transacao.validators.csv_file.is_file_empty], verbose_name='Arquivo'),
        ),
    ]
