# Generated by Django 3.2.13 on 2022-04-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0005_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='agencia_destino',
            field=models.CharField(max_length=10, verbose_name='Agência destino'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='agencia_origem',
            field=models.CharField(max_length=10, verbose_name='Agência origem'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='banco_destino',
            field=models.CharField(max_length=30, verbose_name='Banco destino'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='banco_origem',
            field=models.CharField(max_length=30, verbose_name='Banco origem'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_destino',
            field=models.CharField(max_length=20, verbose_name='Conta destino'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta_origem',
            field=models.CharField(max_length=20, verbose_name='Conta origem'),
        ),
    ]
