# Generated by Django 3.2.13 on 2022-04-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos_csv/', verbose_name='Arquivo'),
        ),
    ]
