# Generated by Django 3.2.13 on 2022-04-12 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transacao', '0002_alter_arquivo_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=3, verbose_name='Banco origem')),
                ('agencia_origem', models.CharField(max_length=4, verbose_name='Agência origem')),
                ('conta_origem', models.CharField(max_length=10, verbose_name='Conta origem')),
                ('banco_destino', models.CharField(max_length=3, verbose_name='Banco destino')),
                ('agencia_destino', models.CharField(max_length=4, verbose_name='Agência destino')),
                ('conta_destino', models.CharField(max_length=10, verbose_name='Conta destino')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transacao.arquivo', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['data_hora'],
            },
        ),
    ]
